# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.10.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.10.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/user/Desktop/paper-version-1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/user/Desktop/paper-version-1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.10.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.10.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.10.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.10.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/local/Cellar/cmake/3.10.2/bin/cpack --config ./CPackSourceConfig.cmake /Users/user/Desktop/paper-version-1/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.10.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.10.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.10.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.10.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/local/Cellar/cmake/3.10.2/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/user/Desktop/paper-version-1/CMakeFiles /Users/user/Desktop/paper-version-1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/user/Desktop/paper-version-1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named paper_node

# Build rule for target.
paper_node: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 paper_node
.PHONY : paper_node

# fast build rule for target.
paper_node/fast:
	$(MAKE) -f CMakeFiles/paper_node.dir/build.make CMakeFiles/paper_node.dir/build
.PHONY : paper_node/fast

#=============================================================================
# Target rules for targets named paper_lib

# Build rule for target.
paper_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 paper_lib
.PHONY : paper_lib

# fast build rule for target.
paper_lib/fast:
	$(MAKE) -f CMakeFiles/paper_lib.dir/build.make CMakeFiles/paper_lib.dir/build
.PHONY : paper_lib/fast

#=============================================================================
# Target rules for targets named blake2

# Build rule for target.
blake2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blake2
.PHONY : blake2

# fast build rule for target.
blake2/fast:
	$(MAKE) -f CMakeFiles/blake2.dir/build.make CMakeFiles/blake2.dir/build
.PHONY : blake2/fast

#=============================================================================
# Target rules for targets named paper_lib_static

# Build rule for target.
paper_lib_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 paper_lib_static
.PHONY : paper_lib_static

# fast build rule for target.
paper_lib_static/fast:
	$(MAKE) -f CMakeFiles/paper_lib_static.dir/build.make CMakeFiles/paper_lib_static.dir/build
.PHONY : paper_lib_static/fast

#=============================================================================
# Target rules for targets named secure

# Build rule for target.
secure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 secure
.PHONY : secure

# fast build rule for target.
secure/fast:
	$(MAKE) -f CMakeFiles/secure.dir/build.make CMakeFiles/secure.dir/build
.PHONY : secure/fast

#=============================================================================
# Target rules for targets named ed25519

# Build rule for target.
ed25519: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ed25519
.PHONY : ed25519

# fast build rule for target.
ed25519/fast:
	$(MAKE) -f CMakeFiles/ed25519.dir/build.make CMakeFiles/ed25519.dir/build
.PHONY : ed25519/fast

#=============================================================================
# Target rules for targets named lmdb

# Build rule for target.
lmdb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lmdb
.PHONY : lmdb

# fast build rule for target.
lmdb/fast:
	$(MAKE) -f CMakeFiles/lmdb.dir/build.make CMakeFiles/lmdb.dir/build
.PHONY : lmdb/fast

#=============================================================================
# Target rules for targets named xxhash

# Build rule for target.
xxhash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xxhash
.PHONY : xxhash

# fast build rule for target.
xxhash/fast:
	$(MAKE) -f CMakeFiles/xxhash.dir/build.make CMakeFiles/xxhash.dir/build
.PHONY : xxhash/fast

#=============================================================================
# Target rules for targets named node

# Build rule for target.
node: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 node
.PHONY : node

# fast build rule for target.
node/fast:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/build
.PHONY : node/fast

#=============================================================================
# Target rules for targets named argon2

# Build rule for target.
argon2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 argon2
.PHONY : argon2

# fast build rule for target.
argon2/fast:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/build
.PHONY : argon2/fast

#=============================================================================
# Target rules for targets named cryptopp

# Build rule for target.
cryptopp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cryptopp
.PHONY : cryptopp

# fast build rule for target.
cryptopp/fast:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/build
.PHONY : cryptopp/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f gtest/CMakeFiles/gtest_main.dir/build.make gtest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f gtest/CMakeFiles/gtest.dir/build.make gtest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named testupnpreplyparse

# Build rule for target.
testupnpreplyparse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testupnpreplyparse
.PHONY : testupnpreplyparse

# fast build rule for target.
testupnpreplyparse/fast:
	$(MAKE) -f miniupnp/miniupnpc/CMakeFiles/testupnpreplyparse.dir/build.make miniupnp/miniupnpc/CMakeFiles/testupnpreplyparse.dir/build
.PHONY : testupnpreplyparse/fast

#=============================================================================
# Target rules for targets named testminiwget

# Build rule for target.
testminiwget: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testminiwget
.PHONY : testminiwget

# fast build rule for target.
testminiwget/fast:
	$(MAKE) -f miniupnp/miniupnpc/CMakeFiles/testminiwget.dir/build.make miniupnp/miniupnpc/CMakeFiles/testminiwget.dir/build
.PHONY : testminiwget/fast

#=============================================================================
# Target rules for targets named testigddescparse

# Build rule for target.
testigddescparse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testigddescparse
.PHONY : testigddescparse

# fast build rule for target.
testigddescparse/fast:
	$(MAKE) -f miniupnp/miniupnpc/CMakeFiles/testigddescparse.dir/build.make miniupnp/miniupnpc/CMakeFiles/testigddescparse.dir/build
.PHONY : testigddescparse/fast

#=============================================================================
# Target rules for targets named upnpc-static

# Build rule for target.
upnpc-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 upnpc-static
.PHONY : upnpc-static

# fast build rule for target.
upnpc-static/fast:
	$(MAKE) -f miniupnp/miniupnpc/CMakeFiles/upnpc-static.dir/build.make miniupnp/miniupnpc/CMakeFiles/upnpc-static.dir/build
.PHONY : upnpc-static/fast

#=============================================================================
# Target rules for targets named minixmlvalid

# Build rule for target.
minixmlvalid: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 minixmlvalid
.PHONY : minixmlvalid

# fast build rule for target.
minixmlvalid/fast:
	$(MAKE) -f miniupnp/miniupnpc/CMakeFiles/minixmlvalid.dir/build.make miniupnp/miniupnpc/CMakeFiles/minixmlvalid.dir/build
.PHONY : minixmlvalid/fast

#=============================================================================
# Target rules for targets named testminixml

# Build rule for target.
testminixml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testminixml
.PHONY : testminixml

# fast build rule for target.
testminixml/fast:
	$(MAKE) -f miniupnp/miniupnpc/CMakeFiles/testminixml.dir/build.make miniupnp/miniupnpc/CMakeFiles/testminixml.dir/build
.PHONY : testminixml/fast

#=============================================================================
# Target rules for targets named libminiupnpc-static

# Build rule for target.
libminiupnpc-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libminiupnpc-static
.PHONY : libminiupnpc-static

# fast build rule for target.
libminiupnpc-static/fast:
	$(MAKE) -f miniupnp/miniupnpc/CMakeFiles/libminiupnpc-static.dir/build.make miniupnp/miniupnpc/CMakeFiles/libminiupnpc-static.dir/build
.PHONY : libminiupnpc-static/fast

blake2/blake2b.o: blake2/blake2b.c.o

.PHONY : blake2/blake2b.o

# target to build an object file
blake2/blake2b.c.o:
	$(MAKE) -f CMakeFiles/blake2.dir/build.make CMakeFiles/blake2.dir/blake2/blake2b.c.o
.PHONY : blake2/blake2b.c.o

blake2/blake2b.i: blake2/blake2b.c.i

.PHONY : blake2/blake2b.i

# target to preprocess a source file
blake2/blake2b.c.i:
	$(MAKE) -f CMakeFiles/blake2.dir/build.make CMakeFiles/blake2.dir/blake2/blake2b.c.i
.PHONY : blake2/blake2b.c.i

blake2/blake2b.s: blake2/blake2b.c.s

.PHONY : blake2/blake2b.s

# target to generate assembly for a file
blake2/blake2b.c.s:
	$(MAKE) -f CMakeFiles/blake2.dir/build.make CMakeFiles/blake2.dir/blake2/blake2b.c.s
.PHONY : blake2/blake2b.c.s

bootstrap_weights.o: bootstrap_weights.cpp.o

.PHONY : bootstrap_weights.o

# target to build an object file
bootstrap_weights.cpp.o:
	$(MAKE) -f CMakeFiles/secure.dir/build.make CMakeFiles/secure.dir/bootstrap_weights.cpp.o
.PHONY : bootstrap_weights.cpp.o

bootstrap_weights.i: bootstrap_weights.cpp.i

.PHONY : bootstrap_weights.i

# target to preprocess a source file
bootstrap_weights.cpp.i:
	$(MAKE) -f CMakeFiles/secure.dir/build.make CMakeFiles/secure.dir/bootstrap_weights.cpp.i
.PHONY : bootstrap_weights.cpp.i

bootstrap_weights.s: bootstrap_weights.cpp.s

.PHONY : bootstrap_weights.s

# target to generate assembly for a file
bootstrap_weights.cpp.s:
	$(MAKE) -f CMakeFiles/secure.dir/build.make CMakeFiles/secure.dir/bootstrap_weights.cpp.s
.PHONY : bootstrap_weights.cpp.s

cryptopp/algparam.o: cryptopp/algparam.cpp.o

.PHONY : cryptopp/algparam.o

# target to build an object file
cryptopp/algparam.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/algparam.cpp.o
.PHONY : cryptopp/algparam.cpp.o

cryptopp/algparam.i: cryptopp/algparam.cpp.i

.PHONY : cryptopp/algparam.i

# target to preprocess a source file
cryptopp/algparam.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/algparam.cpp.i
.PHONY : cryptopp/algparam.cpp.i

cryptopp/algparam.s: cryptopp/algparam.cpp.s

.PHONY : cryptopp/algparam.s

# target to generate assembly for a file
cryptopp/algparam.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/algparam.cpp.s
.PHONY : cryptopp/algparam.cpp.s

cryptopp/asn.o: cryptopp/asn.cpp.o

.PHONY : cryptopp/asn.o

# target to build an object file
cryptopp/asn.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/asn.cpp.o
.PHONY : cryptopp/asn.cpp.o

cryptopp/asn.i: cryptopp/asn.cpp.i

.PHONY : cryptopp/asn.i

# target to preprocess a source file
cryptopp/asn.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/asn.cpp.i
.PHONY : cryptopp/asn.cpp.i

cryptopp/asn.s: cryptopp/asn.cpp.s

.PHONY : cryptopp/asn.s

# target to generate assembly for a file
cryptopp/asn.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/asn.cpp.s
.PHONY : cryptopp/asn.cpp.s

cryptopp/basecode.o: cryptopp/basecode.cpp.o

.PHONY : cryptopp/basecode.o

# target to build an object file
cryptopp/basecode.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/basecode.cpp.o
.PHONY : cryptopp/basecode.cpp.o

cryptopp/basecode.i: cryptopp/basecode.cpp.i

.PHONY : cryptopp/basecode.i

# target to preprocess a source file
cryptopp/basecode.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/basecode.cpp.i
.PHONY : cryptopp/basecode.cpp.i

cryptopp/basecode.s: cryptopp/basecode.cpp.s

.PHONY : cryptopp/basecode.s

# target to generate assembly for a file
cryptopp/basecode.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/basecode.cpp.s
.PHONY : cryptopp/basecode.cpp.s

cryptopp/cpu.o: cryptopp/cpu.cpp.o

.PHONY : cryptopp/cpu.o

# target to build an object file
cryptopp/cpu.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/cpu.cpp.o
.PHONY : cryptopp/cpu.cpp.o

cryptopp/cpu.i: cryptopp/cpu.cpp.i

.PHONY : cryptopp/cpu.i

# target to preprocess a source file
cryptopp/cpu.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/cpu.cpp.i
.PHONY : cryptopp/cpu.cpp.i

cryptopp/cpu.s: cryptopp/cpu.cpp.s

.PHONY : cryptopp/cpu.s

# target to generate assembly for a file
cryptopp/cpu.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/cpu.cpp.s
.PHONY : cryptopp/cpu.cpp.s

cryptopp/cryptlib.o: cryptopp/cryptlib.cpp.o

.PHONY : cryptopp/cryptlib.o

# target to build an object file
cryptopp/cryptlib.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/cryptlib.cpp.o
.PHONY : cryptopp/cryptlib.cpp.o

cryptopp/cryptlib.i: cryptopp/cryptlib.cpp.i

.PHONY : cryptopp/cryptlib.i

# target to preprocess a source file
cryptopp/cryptlib.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/cryptlib.cpp.i
.PHONY : cryptopp/cryptlib.cpp.i

cryptopp/cryptlib.s: cryptopp/cryptlib.cpp.s

.PHONY : cryptopp/cryptlib.s

# target to generate assembly for a file
cryptopp/cryptlib.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/cryptlib.cpp.s
.PHONY : cryptopp/cryptlib.cpp.s

cryptopp/default.o: cryptopp/default.cpp.o

.PHONY : cryptopp/default.o

# target to build an object file
cryptopp/default.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/default.cpp.o
.PHONY : cryptopp/default.cpp.o

cryptopp/default.i: cryptopp/default.cpp.i

.PHONY : cryptopp/default.i

# target to preprocess a source file
cryptopp/default.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/default.cpp.i
.PHONY : cryptopp/default.cpp.i

cryptopp/default.s: cryptopp/default.cpp.s

.PHONY : cryptopp/default.s

# target to generate assembly for a file
cryptopp/default.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/default.cpp.s
.PHONY : cryptopp/default.cpp.s

cryptopp/des.o: cryptopp/des.cpp.o

.PHONY : cryptopp/des.o

# target to build an object file
cryptopp/des.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/des.cpp.o
.PHONY : cryptopp/des.cpp.o

cryptopp/des.i: cryptopp/des.cpp.i

.PHONY : cryptopp/des.i

# target to preprocess a source file
cryptopp/des.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/des.cpp.i
.PHONY : cryptopp/des.cpp.i

cryptopp/des.s: cryptopp/des.cpp.s

.PHONY : cryptopp/des.s

# target to generate assembly for a file
cryptopp/des.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/des.cpp.s
.PHONY : cryptopp/des.cpp.s

cryptopp/dessp.o: cryptopp/dessp.cpp.o

.PHONY : cryptopp/dessp.o

# target to build an object file
cryptopp/dessp.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/dessp.cpp.o
.PHONY : cryptopp/dessp.cpp.o

cryptopp/dessp.i: cryptopp/dessp.cpp.i

.PHONY : cryptopp/dessp.i

# target to preprocess a source file
cryptopp/dessp.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/dessp.cpp.i
.PHONY : cryptopp/dessp.cpp.i

cryptopp/dessp.s: cryptopp/dessp.cpp.s

.PHONY : cryptopp/dessp.s

# target to generate assembly for a file
cryptopp/dessp.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/dessp.cpp.s
.PHONY : cryptopp/dessp.cpp.s

cryptopp/dll.o: cryptopp/dll.cpp.o

.PHONY : cryptopp/dll.o

# target to build an object file
cryptopp/dll.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/dll.cpp.o
.PHONY : cryptopp/dll.cpp.o

cryptopp/dll.i: cryptopp/dll.cpp.i

.PHONY : cryptopp/dll.i

# target to preprocess a source file
cryptopp/dll.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/dll.cpp.i
.PHONY : cryptopp/dll.cpp.i

cryptopp/dll.s: cryptopp/dll.cpp.s

.PHONY : cryptopp/dll.s

# target to generate assembly for a file
cryptopp/dll.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/dll.cpp.s
.PHONY : cryptopp/dll.cpp.s

cryptopp/ec2n.o: cryptopp/ec2n.cpp.o

.PHONY : cryptopp/ec2n.o

# target to build an object file
cryptopp/ec2n.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/ec2n.cpp.o
.PHONY : cryptopp/ec2n.cpp.o

cryptopp/ec2n.i: cryptopp/ec2n.cpp.i

.PHONY : cryptopp/ec2n.i

# target to preprocess a source file
cryptopp/ec2n.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/ec2n.cpp.i
.PHONY : cryptopp/ec2n.cpp.i

cryptopp/ec2n.s: cryptopp/ec2n.cpp.s

.PHONY : cryptopp/ec2n.s

# target to generate assembly for a file
cryptopp/ec2n.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/ec2n.cpp.s
.PHONY : cryptopp/ec2n.cpp.s

cryptopp/ecp.o: cryptopp/ecp.cpp.o

.PHONY : cryptopp/ecp.o

# target to build an object file
cryptopp/ecp.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/ecp.cpp.o
.PHONY : cryptopp/ecp.cpp.o

cryptopp/ecp.i: cryptopp/ecp.cpp.i

.PHONY : cryptopp/ecp.i

# target to preprocess a source file
cryptopp/ecp.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/ecp.cpp.i
.PHONY : cryptopp/ecp.cpp.i

cryptopp/ecp.s: cryptopp/ecp.cpp.s

.PHONY : cryptopp/ecp.s

# target to generate assembly for a file
cryptopp/ecp.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/ecp.cpp.s
.PHONY : cryptopp/ecp.cpp.s

cryptopp/filters.o: cryptopp/filters.cpp.o

.PHONY : cryptopp/filters.o

# target to build an object file
cryptopp/filters.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/filters.cpp.o
.PHONY : cryptopp/filters.cpp.o

cryptopp/filters.i: cryptopp/filters.cpp.i

.PHONY : cryptopp/filters.i

# target to preprocess a source file
cryptopp/filters.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/filters.cpp.i
.PHONY : cryptopp/filters.cpp.i

cryptopp/filters.s: cryptopp/filters.cpp.s

.PHONY : cryptopp/filters.s

# target to generate assembly for a file
cryptopp/filters.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/filters.cpp.s
.PHONY : cryptopp/filters.cpp.s

cryptopp/fips140.o: cryptopp/fips140.cpp.o

.PHONY : cryptopp/fips140.o

# target to build an object file
cryptopp/fips140.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/fips140.cpp.o
.PHONY : cryptopp/fips140.cpp.o

cryptopp/fips140.i: cryptopp/fips140.cpp.i

.PHONY : cryptopp/fips140.i

# target to preprocess a source file
cryptopp/fips140.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/fips140.cpp.i
.PHONY : cryptopp/fips140.cpp.i

cryptopp/fips140.s: cryptopp/fips140.cpp.s

.PHONY : cryptopp/fips140.s

# target to generate assembly for a file
cryptopp/fips140.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/fips140.cpp.s
.PHONY : cryptopp/fips140.cpp.s

cryptopp/gcm.o: cryptopp/gcm.cpp.o

.PHONY : cryptopp/gcm.o

# target to build an object file
cryptopp/gcm.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/gcm.cpp.o
.PHONY : cryptopp/gcm.cpp.o

cryptopp/gcm.i: cryptopp/gcm.cpp.i

.PHONY : cryptopp/gcm.i

# target to preprocess a source file
cryptopp/gcm.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/gcm.cpp.i
.PHONY : cryptopp/gcm.cpp.i

cryptopp/gcm.s: cryptopp/gcm.cpp.s

.PHONY : cryptopp/gcm.s

# target to generate assembly for a file
cryptopp/gcm.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/gcm.cpp.s
.PHONY : cryptopp/gcm.cpp.s

cryptopp/gf2n.o: cryptopp/gf2n.cpp.o

.PHONY : cryptopp/gf2n.o

# target to build an object file
cryptopp/gf2n.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/gf2n.cpp.o
.PHONY : cryptopp/gf2n.cpp.o

cryptopp/gf2n.i: cryptopp/gf2n.cpp.i

.PHONY : cryptopp/gf2n.i

# target to preprocess a source file
cryptopp/gf2n.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/gf2n.cpp.i
.PHONY : cryptopp/gf2n.cpp.i

cryptopp/gf2n.s: cryptopp/gf2n.cpp.s

.PHONY : cryptopp/gf2n.s

# target to generate assembly for a file
cryptopp/gf2n.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/gf2n.cpp.s
.PHONY : cryptopp/gf2n.cpp.s

cryptopp/gfpcrypt.o: cryptopp/gfpcrypt.cpp.o

.PHONY : cryptopp/gfpcrypt.o

# target to build an object file
cryptopp/gfpcrypt.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/gfpcrypt.cpp.o
.PHONY : cryptopp/gfpcrypt.cpp.o

cryptopp/gfpcrypt.i: cryptopp/gfpcrypt.cpp.i

.PHONY : cryptopp/gfpcrypt.i

# target to preprocess a source file
cryptopp/gfpcrypt.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/gfpcrypt.cpp.i
.PHONY : cryptopp/gfpcrypt.cpp.i

cryptopp/gfpcrypt.s: cryptopp/gfpcrypt.cpp.s

.PHONY : cryptopp/gfpcrypt.s

# target to generate assembly for a file
cryptopp/gfpcrypt.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/gfpcrypt.cpp.s
.PHONY : cryptopp/gfpcrypt.cpp.s

cryptopp/hex.o: cryptopp/hex.cpp.o

.PHONY : cryptopp/hex.o

# target to build an object file
cryptopp/hex.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/hex.cpp.o
.PHONY : cryptopp/hex.cpp.o

cryptopp/hex.i: cryptopp/hex.cpp.i

.PHONY : cryptopp/hex.i

# target to preprocess a source file
cryptopp/hex.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/hex.cpp.i
.PHONY : cryptopp/hex.cpp.i

cryptopp/hex.s: cryptopp/hex.cpp.s

.PHONY : cryptopp/hex.s

# target to generate assembly for a file
cryptopp/hex.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/hex.cpp.s
.PHONY : cryptopp/hex.cpp.s

cryptopp/hmac.o: cryptopp/hmac.cpp.o

.PHONY : cryptopp/hmac.o

# target to build an object file
cryptopp/hmac.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/hmac.cpp.o
.PHONY : cryptopp/hmac.cpp.o

cryptopp/hmac.i: cryptopp/hmac.cpp.i

.PHONY : cryptopp/hmac.i

# target to preprocess a source file
cryptopp/hmac.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/hmac.cpp.i
.PHONY : cryptopp/hmac.cpp.i

cryptopp/hmac.s: cryptopp/hmac.cpp.s

.PHONY : cryptopp/hmac.s

# target to generate assembly for a file
cryptopp/hmac.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/hmac.cpp.s
.PHONY : cryptopp/hmac.cpp.s

cryptopp/hrtimer.o: cryptopp/hrtimer.cpp.o

.PHONY : cryptopp/hrtimer.o

# target to build an object file
cryptopp/hrtimer.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/hrtimer.cpp.o
.PHONY : cryptopp/hrtimer.cpp.o

cryptopp/hrtimer.i: cryptopp/hrtimer.cpp.i

.PHONY : cryptopp/hrtimer.i

# target to preprocess a source file
cryptopp/hrtimer.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/hrtimer.cpp.i
.PHONY : cryptopp/hrtimer.cpp.i

cryptopp/hrtimer.s: cryptopp/hrtimer.cpp.s

.PHONY : cryptopp/hrtimer.s

# target to generate assembly for a file
cryptopp/hrtimer.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/hrtimer.cpp.s
.PHONY : cryptopp/hrtimer.cpp.s

cryptopp/integer.o: cryptopp/integer.cpp.o

.PHONY : cryptopp/integer.o

# target to build an object file
cryptopp/integer.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/integer.cpp.o
.PHONY : cryptopp/integer.cpp.o

cryptopp/integer.i: cryptopp/integer.cpp.i

.PHONY : cryptopp/integer.i

# target to preprocess a source file
cryptopp/integer.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/integer.cpp.i
.PHONY : cryptopp/integer.cpp.i

cryptopp/integer.s: cryptopp/integer.cpp.s

.PHONY : cryptopp/integer.s

# target to generate assembly for a file
cryptopp/integer.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/integer.cpp.s
.PHONY : cryptopp/integer.cpp.s

cryptopp/iterhash.o: cryptopp/iterhash.cpp.o

.PHONY : cryptopp/iterhash.o

# target to build an object file
cryptopp/iterhash.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/iterhash.cpp.o
.PHONY : cryptopp/iterhash.cpp.o

cryptopp/iterhash.i: cryptopp/iterhash.cpp.i

.PHONY : cryptopp/iterhash.i

# target to preprocess a source file
cryptopp/iterhash.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/iterhash.cpp.i
.PHONY : cryptopp/iterhash.cpp.i

cryptopp/iterhash.s: cryptopp/iterhash.cpp.s

.PHONY : cryptopp/iterhash.s

# target to generate assembly for a file
cryptopp/iterhash.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/iterhash.cpp.s
.PHONY : cryptopp/iterhash.cpp.s

cryptopp/misc.o: cryptopp/misc.cpp.o

.PHONY : cryptopp/misc.o

# target to build an object file
cryptopp/misc.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/misc.cpp.o
.PHONY : cryptopp/misc.cpp.o

cryptopp/misc.i: cryptopp/misc.cpp.i

.PHONY : cryptopp/misc.i

# target to preprocess a source file
cryptopp/misc.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/misc.cpp.i
.PHONY : cryptopp/misc.cpp.i

cryptopp/misc.s: cryptopp/misc.cpp.s

.PHONY : cryptopp/misc.s

# target to generate assembly for a file
cryptopp/misc.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/misc.cpp.s
.PHONY : cryptopp/misc.cpp.s

cryptopp/modes.o: cryptopp/modes.cpp.o

.PHONY : cryptopp/modes.o

# target to build an object file
cryptopp/modes.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/modes.cpp.o
.PHONY : cryptopp/modes.cpp.o

cryptopp/modes.i: cryptopp/modes.cpp.i

.PHONY : cryptopp/modes.i

# target to preprocess a source file
cryptopp/modes.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/modes.cpp.i
.PHONY : cryptopp/modes.cpp.i

cryptopp/modes.s: cryptopp/modes.cpp.s

.PHONY : cryptopp/modes.s

# target to generate assembly for a file
cryptopp/modes.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/modes.cpp.s
.PHONY : cryptopp/modes.cpp.s

cryptopp/mqueue.o: cryptopp/mqueue.cpp.o

.PHONY : cryptopp/mqueue.o

# target to build an object file
cryptopp/mqueue.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/mqueue.cpp.o
.PHONY : cryptopp/mqueue.cpp.o

cryptopp/mqueue.i: cryptopp/mqueue.cpp.i

.PHONY : cryptopp/mqueue.i

# target to preprocess a source file
cryptopp/mqueue.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/mqueue.cpp.i
.PHONY : cryptopp/mqueue.cpp.i

cryptopp/mqueue.s: cryptopp/mqueue.cpp.s

.PHONY : cryptopp/mqueue.s

# target to generate assembly for a file
cryptopp/mqueue.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/mqueue.cpp.s
.PHONY : cryptopp/mqueue.cpp.s

cryptopp/nbtheory.o: cryptopp/nbtheory.cpp.o

.PHONY : cryptopp/nbtheory.o

# target to build an object file
cryptopp/nbtheory.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/nbtheory.cpp.o
.PHONY : cryptopp/nbtheory.cpp.o

cryptopp/nbtheory.i: cryptopp/nbtheory.cpp.i

.PHONY : cryptopp/nbtheory.i

# target to preprocess a source file
cryptopp/nbtheory.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/nbtheory.cpp.i
.PHONY : cryptopp/nbtheory.cpp.i

cryptopp/nbtheory.s: cryptopp/nbtheory.cpp.s

.PHONY : cryptopp/nbtheory.s

# target to generate assembly for a file
cryptopp/nbtheory.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/nbtheory.cpp.s
.PHONY : cryptopp/nbtheory.cpp.s

cryptopp/oaep.o: cryptopp/oaep.cpp.o

.PHONY : cryptopp/oaep.o

# target to build an object file
cryptopp/oaep.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/oaep.cpp.o
.PHONY : cryptopp/oaep.cpp.o

cryptopp/oaep.i: cryptopp/oaep.cpp.i

.PHONY : cryptopp/oaep.i

# target to preprocess a source file
cryptopp/oaep.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/oaep.cpp.i
.PHONY : cryptopp/oaep.cpp.i

cryptopp/oaep.s: cryptopp/oaep.cpp.s

.PHONY : cryptopp/oaep.s

# target to generate assembly for a file
cryptopp/oaep.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/oaep.cpp.s
.PHONY : cryptopp/oaep.cpp.s

cryptopp/osrng.o: cryptopp/osrng.cpp.o

.PHONY : cryptopp/osrng.o

# target to build an object file
cryptopp/osrng.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/osrng.cpp.o
.PHONY : cryptopp/osrng.cpp.o

cryptopp/osrng.i: cryptopp/osrng.cpp.i

.PHONY : cryptopp/osrng.i

# target to preprocess a source file
cryptopp/osrng.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/osrng.cpp.i
.PHONY : cryptopp/osrng.cpp.i

cryptopp/osrng.s: cryptopp/osrng.cpp.s

.PHONY : cryptopp/osrng.s

# target to generate assembly for a file
cryptopp/osrng.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/osrng.cpp.s
.PHONY : cryptopp/osrng.cpp.s

cryptopp/pubkey.o: cryptopp/pubkey.cpp.o

.PHONY : cryptopp/pubkey.o

# target to build an object file
cryptopp/pubkey.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/pubkey.cpp.o
.PHONY : cryptopp/pubkey.cpp.o

cryptopp/pubkey.i: cryptopp/pubkey.cpp.i

.PHONY : cryptopp/pubkey.i

# target to preprocess a source file
cryptopp/pubkey.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/pubkey.cpp.i
.PHONY : cryptopp/pubkey.cpp.i

cryptopp/pubkey.s: cryptopp/pubkey.cpp.s

.PHONY : cryptopp/pubkey.s

# target to generate assembly for a file
cryptopp/pubkey.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/pubkey.cpp.s
.PHONY : cryptopp/pubkey.cpp.s

cryptopp/queue.o: cryptopp/queue.cpp.o

.PHONY : cryptopp/queue.o

# target to build an object file
cryptopp/queue.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/queue.cpp.o
.PHONY : cryptopp/queue.cpp.o

cryptopp/queue.i: cryptopp/queue.cpp.i

.PHONY : cryptopp/queue.i

# target to preprocess a source file
cryptopp/queue.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/queue.cpp.i
.PHONY : cryptopp/queue.cpp.i

cryptopp/queue.s: cryptopp/queue.cpp.s

.PHONY : cryptopp/queue.s

# target to generate assembly for a file
cryptopp/queue.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/queue.cpp.s
.PHONY : cryptopp/queue.cpp.s

cryptopp/randpool.o: cryptopp/randpool.cpp.o

.PHONY : cryptopp/randpool.o

# target to build an object file
cryptopp/randpool.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/randpool.cpp.o
.PHONY : cryptopp/randpool.cpp.o

cryptopp/randpool.i: cryptopp/randpool.cpp.i

.PHONY : cryptopp/randpool.i

# target to preprocess a source file
cryptopp/randpool.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/randpool.cpp.i
.PHONY : cryptopp/randpool.cpp.i

cryptopp/randpool.s: cryptopp/randpool.cpp.s

.PHONY : cryptopp/randpool.s

# target to generate assembly for a file
cryptopp/randpool.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/randpool.cpp.s
.PHONY : cryptopp/randpool.cpp.s

cryptopp/rdtables.o: cryptopp/rdtables.cpp.o

.PHONY : cryptopp/rdtables.o

# target to build an object file
cryptopp/rdtables.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/rdtables.cpp.o
.PHONY : cryptopp/rdtables.cpp.o

cryptopp/rdtables.i: cryptopp/rdtables.cpp.i

.PHONY : cryptopp/rdtables.i

# target to preprocess a source file
cryptopp/rdtables.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/rdtables.cpp.i
.PHONY : cryptopp/rdtables.cpp.i

cryptopp/rdtables.s: cryptopp/rdtables.cpp.s

.PHONY : cryptopp/rdtables.s

# target to generate assembly for a file
cryptopp/rdtables.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/rdtables.cpp.s
.PHONY : cryptopp/rdtables.cpp.s

cryptopp/rijndael.o: cryptopp/rijndael.cpp.o

.PHONY : cryptopp/rijndael.o

# target to build an object file
cryptopp/rijndael.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/rijndael.cpp.o
.PHONY : cryptopp/rijndael.cpp.o

cryptopp/rijndael.i: cryptopp/rijndael.cpp.i

.PHONY : cryptopp/rijndael.i

# target to preprocess a source file
cryptopp/rijndael.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/rijndael.cpp.i
.PHONY : cryptopp/rijndael.cpp.i

cryptopp/rijndael.s: cryptopp/rijndael.cpp.s

.PHONY : cryptopp/rijndael.s

# target to generate assembly for a file
cryptopp/rijndael.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/rijndael.cpp.s
.PHONY : cryptopp/rijndael.cpp.s

cryptopp/rng.o: cryptopp/rng.cpp.o

.PHONY : cryptopp/rng.o

# target to build an object file
cryptopp/rng.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/rng.cpp.o
.PHONY : cryptopp/rng.cpp.o

cryptopp/rng.i: cryptopp/rng.cpp.i

.PHONY : cryptopp/rng.i

# target to preprocess a source file
cryptopp/rng.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/rng.cpp.i
.PHONY : cryptopp/rng.cpp.i

cryptopp/rng.s: cryptopp/rng.cpp.s

.PHONY : cryptopp/rng.s

# target to generate assembly for a file
cryptopp/rng.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/rng.cpp.s
.PHONY : cryptopp/rng.cpp.s

cryptopp/sha.o: cryptopp/sha.cpp.o

.PHONY : cryptopp/sha.o

# target to build an object file
cryptopp/sha.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/sha.cpp.o
.PHONY : cryptopp/sha.cpp.o

cryptopp/sha.i: cryptopp/sha.cpp.i

.PHONY : cryptopp/sha.i

# target to preprocess a source file
cryptopp/sha.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/sha.cpp.i
.PHONY : cryptopp/sha.cpp.i

cryptopp/sha.s: cryptopp/sha.cpp.s

.PHONY : cryptopp/sha.s

# target to generate assembly for a file
cryptopp/sha.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/sha.cpp.s
.PHONY : cryptopp/sha.cpp.s

cryptopp/simple.o: cryptopp/simple.cpp.o

.PHONY : cryptopp/simple.o

# target to build an object file
cryptopp/simple.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/simple.cpp.o
.PHONY : cryptopp/simple.cpp.o

cryptopp/simple.i: cryptopp/simple.cpp.i

.PHONY : cryptopp/simple.i

# target to preprocess a source file
cryptopp/simple.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/simple.cpp.i
.PHONY : cryptopp/simple.cpp.i

cryptopp/simple.s: cryptopp/simple.cpp.s

.PHONY : cryptopp/simple.s

# target to generate assembly for a file
cryptopp/simple.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/simple.cpp.s
.PHONY : cryptopp/simple.cpp.s

cryptopp/winpipes.o: cryptopp/winpipes.cpp.o

.PHONY : cryptopp/winpipes.o

# target to build an object file
cryptopp/winpipes.cpp.o:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/winpipes.cpp.o
.PHONY : cryptopp/winpipes.cpp.o

cryptopp/winpipes.i: cryptopp/winpipes.cpp.i

.PHONY : cryptopp/winpipes.i

# target to preprocess a source file
cryptopp/winpipes.cpp.i:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/winpipes.cpp.i
.PHONY : cryptopp/winpipes.cpp.i

cryptopp/winpipes.s: cryptopp/winpipes.cpp.s

.PHONY : cryptopp/winpipes.s

# target to generate assembly for a file
cryptopp/winpipes.cpp.s:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/cryptopp/winpipes.cpp.s
.PHONY : cryptopp/winpipes.cpp.s

ed25519-donna/ed25519.o: ed25519-donna/ed25519.c.o

.PHONY : ed25519-donna/ed25519.o

# target to build an object file
ed25519-donna/ed25519.c.o:
	$(MAKE) -f CMakeFiles/ed25519.dir/build.make CMakeFiles/ed25519.dir/ed25519-donna/ed25519.c.o
.PHONY : ed25519-donna/ed25519.c.o

ed25519-donna/ed25519.i: ed25519-donna/ed25519.c.i

.PHONY : ed25519-donna/ed25519.i

# target to preprocess a source file
ed25519-donna/ed25519.c.i:
	$(MAKE) -f CMakeFiles/ed25519.dir/build.make CMakeFiles/ed25519.dir/ed25519-donna/ed25519.c.i
.PHONY : ed25519-donna/ed25519.c.i

ed25519-donna/ed25519.s: ed25519-donna/ed25519.c.s

.PHONY : ed25519-donna/ed25519.s

# target to generate assembly for a file
ed25519-donna/ed25519.c.s:
	$(MAKE) -f CMakeFiles/ed25519.dir/build.make CMakeFiles/ed25519.dir/ed25519-donna/ed25519.c.s
.PHONY : ed25519-donna/ed25519.c.s

lmdb/libraries/liblmdb/mdb.o: lmdb/libraries/liblmdb/mdb.c.o

.PHONY : lmdb/libraries/liblmdb/mdb.o

# target to build an object file
lmdb/libraries/liblmdb/mdb.c.o:
	$(MAKE) -f CMakeFiles/lmdb.dir/build.make CMakeFiles/lmdb.dir/lmdb/libraries/liblmdb/mdb.c.o
.PHONY : lmdb/libraries/liblmdb/mdb.c.o

lmdb/libraries/liblmdb/mdb.i: lmdb/libraries/liblmdb/mdb.c.i

.PHONY : lmdb/libraries/liblmdb/mdb.i

# target to preprocess a source file
lmdb/libraries/liblmdb/mdb.c.i:
	$(MAKE) -f CMakeFiles/lmdb.dir/build.make CMakeFiles/lmdb.dir/lmdb/libraries/liblmdb/mdb.c.i
.PHONY : lmdb/libraries/liblmdb/mdb.c.i

lmdb/libraries/liblmdb/mdb.s: lmdb/libraries/liblmdb/mdb.c.s

.PHONY : lmdb/libraries/liblmdb/mdb.s

# target to generate assembly for a file
lmdb/libraries/liblmdb/mdb.c.s:
	$(MAKE) -f CMakeFiles/lmdb.dir/build.make CMakeFiles/lmdb.dir/lmdb/libraries/liblmdb/mdb.c.s
.PHONY : lmdb/libraries/liblmdb/mdb.c.s

lmdb/libraries/liblmdb/midl.o: lmdb/libraries/liblmdb/midl.c.o

.PHONY : lmdb/libraries/liblmdb/midl.o

# target to build an object file
lmdb/libraries/liblmdb/midl.c.o:
	$(MAKE) -f CMakeFiles/lmdb.dir/build.make CMakeFiles/lmdb.dir/lmdb/libraries/liblmdb/midl.c.o
.PHONY : lmdb/libraries/liblmdb/midl.c.o

lmdb/libraries/liblmdb/midl.i: lmdb/libraries/liblmdb/midl.c.i

.PHONY : lmdb/libraries/liblmdb/midl.i

# target to preprocess a source file
lmdb/libraries/liblmdb/midl.c.i:
	$(MAKE) -f CMakeFiles/lmdb.dir/build.make CMakeFiles/lmdb.dir/lmdb/libraries/liblmdb/midl.c.i
.PHONY : lmdb/libraries/liblmdb/midl.c.i

lmdb/libraries/liblmdb/midl.s: lmdb/libraries/liblmdb/midl.c.s

.PHONY : lmdb/libraries/liblmdb/midl.s

# target to generate assembly for a file
lmdb/libraries/liblmdb/midl.c.s:
	$(MAKE) -f CMakeFiles/lmdb.dir/build.make CMakeFiles/lmdb.dir/lmdb/libraries/liblmdb/midl.c.s
.PHONY : lmdb/libraries/liblmdb/midl.c.s

paper/blockstore.o: paper/blockstore.cpp.o

.PHONY : paper/blockstore.o

# target to build an object file
paper/blockstore.cpp.o:
	$(MAKE) -f CMakeFiles/secure.dir/build.make CMakeFiles/secure.dir/paper/blockstore.cpp.o
.PHONY : paper/blockstore.cpp.o

paper/blockstore.i: paper/blockstore.cpp.i

.PHONY : paper/blockstore.i

# target to preprocess a source file
paper/blockstore.cpp.i:
	$(MAKE) -f CMakeFiles/secure.dir/build.make CMakeFiles/secure.dir/paper/blockstore.cpp.i
.PHONY : paper/blockstore.cpp.i

paper/blockstore.s: paper/blockstore.cpp.s

.PHONY : paper/blockstore.s

# target to generate assembly for a file
paper/blockstore.cpp.s:
	$(MAKE) -f CMakeFiles/secure.dir/build.make CMakeFiles/secure.dir/paper/blockstore.cpp.s
.PHONY : paper/blockstore.cpp.s

paper/common.o: paper/common.cpp.o

.PHONY : paper/common.o

# target to build an object file
paper/common.cpp.o:
	$(MAKE) -f CMakeFiles/secure.dir/build.make CMakeFiles/secure.dir/paper/common.cpp.o
.PHONY : paper/common.cpp.o

paper/common.i: paper/common.cpp.i

.PHONY : paper/common.i

# target to preprocess a source file
paper/common.cpp.i:
	$(MAKE) -f CMakeFiles/secure.dir/build.make CMakeFiles/secure.dir/paper/common.cpp.i
.PHONY : paper/common.cpp.i

paper/common.s: paper/common.cpp.s

.PHONY : paper/common.s

# target to generate assembly for a file
paper/common.cpp.s:
	$(MAKE) -f CMakeFiles/secure.dir/build.make CMakeFiles/secure.dir/paper/common.cpp.s
.PHONY : paper/common.cpp.s

paper/ledger.o: paper/ledger.cpp.o

.PHONY : paper/ledger.o

# target to build an object file
paper/ledger.cpp.o:
	$(MAKE) -f CMakeFiles/secure.dir/build.make CMakeFiles/secure.dir/paper/ledger.cpp.o
.PHONY : paper/ledger.cpp.o

paper/ledger.i: paper/ledger.cpp.i

.PHONY : paper/ledger.i

# target to preprocess a source file
paper/ledger.cpp.i:
	$(MAKE) -f CMakeFiles/secure.dir/build.make CMakeFiles/secure.dir/paper/ledger.cpp.i
.PHONY : paper/ledger.cpp.i

paper/ledger.s: paper/ledger.cpp.s

.PHONY : paper/ledger.s

# target to generate assembly for a file
paper/ledger.cpp.s:
	$(MAKE) -f CMakeFiles/secure.dir/build.make CMakeFiles/secure.dir/paper/ledger.cpp.s
.PHONY : paper/ledger.cpp.s

paper/lib/blocks.o: paper/lib/blocks.cpp.o

.PHONY : paper/lib/blocks.o

# target to build an object file
paper/lib/blocks.cpp.o:
	$(MAKE) -f CMakeFiles/paper_lib.dir/build.make CMakeFiles/paper_lib.dir/paper/lib/blocks.cpp.o
	$(MAKE) -f CMakeFiles/paper_lib_static.dir/build.make CMakeFiles/paper_lib_static.dir/paper/lib/blocks.cpp.o
.PHONY : paper/lib/blocks.cpp.o

paper/lib/blocks.i: paper/lib/blocks.cpp.i

.PHONY : paper/lib/blocks.i

# target to preprocess a source file
paper/lib/blocks.cpp.i:
	$(MAKE) -f CMakeFiles/paper_lib.dir/build.make CMakeFiles/paper_lib.dir/paper/lib/blocks.cpp.i
	$(MAKE) -f CMakeFiles/paper_lib_static.dir/build.make CMakeFiles/paper_lib_static.dir/paper/lib/blocks.cpp.i
.PHONY : paper/lib/blocks.cpp.i

paper/lib/blocks.s: paper/lib/blocks.cpp.s

.PHONY : paper/lib/blocks.s

# target to generate assembly for a file
paper/lib/blocks.cpp.s:
	$(MAKE) -f CMakeFiles/paper_lib.dir/build.make CMakeFiles/paper_lib.dir/paper/lib/blocks.cpp.s
	$(MAKE) -f CMakeFiles/paper_lib_static.dir/build.make CMakeFiles/paper_lib_static.dir/paper/lib/blocks.cpp.s
.PHONY : paper/lib/blocks.cpp.s

paper/lib/interface.o: paper/lib/interface.cpp.o

.PHONY : paper/lib/interface.o

# target to build an object file
paper/lib/interface.cpp.o:
	$(MAKE) -f CMakeFiles/paper_lib.dir/build.make CMakeFiles/paper_lib.dir/paper/lib/interface.cpp.o
	$(MAKE) -f CMakeFiles/paper_lib_static.dir/build.make CMakeFiles/paper_lib_static.dir/paper/lib/interface.cpp.o
.PHONY : paper/lib/interface.cpp.o

paper/lib/interface.i: paper/lib/interface.cpp.i

.PHONY : paper/lib/interface.i

# target to preprocess a source file
paper/lib/interface.cpp.i:
	$(MAKE) -f CMakeFiles/paper_lib.dir/build.make CMakeFiles/paper_lib.dir/paper/lib/interface.cpp.i
	$(MAKE) -f CMakeFiles/paper_lib_static.dir/build.make CMakeFiles/paper_lib_static.dir/paper/lib/interface.cpp.i
.PHONY : paper/lib/interface.cpp.i

paper/lib/interface.s: paper/lib/interface.cpp.s

.PHONY : paper/lib/interface.s

# target to generate assembly for a file
paper/lib/interface.cpp.s:
	$(MAKE) -f CMakeFiles/paper_lib.dir/build.make CMakeFiles/paper_lib.dir/paper/lib/interface.cpp.s
	$(MAKE) -f CMakeFiles/paper_lib_static.dir/build.make CMakeFiles/paper_lib_static.dir/paper/lib/interface.cpp.s
.PHONY : paper/lib/interface.cpp.s

paper/lib/numbers.o: paper/lib/numbers.cpp.o

.PHONY : paper/lib/numbers.o

# target to build an object file
paper/lib/numbers.cpp.o:
	$(MAKE) -f CMakeFiles/paper_lib.dir/build.make CMakeFiles/paper_lib.dir/paper/lib/numbers.cpp.o
	$(MAKE) -f CMakeFiles/paper_lib_static.dir/build.make CMakeFiles/paper_lib_static.dir/paper/lib/numbers.cpp.o
.PHONY : paper/lib/numbers.cpp.o

paper/lib/numbers.i: paper/lib/numbers.cpp.i

.PHONY : paper/lib/numbers.i

# target to preprocess a source file
paper/lib/numbers.cpp.i:
	$(MAKE) -f CMakeFiles/paper_lib.dir/build.make CMakeFiles/paper_lib.dir/paper/lib/numbers.cpp.i
	$(MAKE) -f CMakeFiles/paper_lib_static.dir/build.make CMakeFiles/paper_lib_static.dir/paper/lib/numbers.cpp.i
.PHONY : paper/lib/numbers.cpp.i

paper/lib/numbers.s: paper/lib/numbers.cpp.s

.PHONY : paper/lib/numbers.s

# target to generate assembly for a file
paper/lib/numbers.cpp.s:
	$(MAKE) -f CMakeFiles/paper_lib.dir/build.make CMakeFiles/paper_lib.dir/paper/lib/numbers.cpp.s
	$(MAKE) -f CMakeFiles/paper_lib_static.dir/build.make CMakeFiles/paper_lib_static.dir/paper/lib/numbers.cpp.s
.PHONY : paper/lib/numbers.cpp.s

paper/lib/utility.o: paper/lib/utility.cpp.o

.PHONY : paper/lib/utility.o

# target to build an object file
paper/lib/utility.cpp.o:
	$(MAKE) -f CMakeFiles/paper_lib.dir/build.make CMakeFiles/paper_lib.dir/paper/lib/utility.cpp.o
	$(MAKE) -f CMakeFiles/paper_lib_static.dir/build.make CMakeFiles/paper_lib_static.dir/paper/lib/utility.cpp.o
.PHONY : paper/lib/utility.cpp.o

paper/lib/utility.i: paper/lib/utility.cpp.i

.PHONY : paper/lib/utility.i

# target to preprocess a source file
paper/lib/utility.cpp.i:
	$(MAKE) -f CMakeFiles/paper_lib.dir/build.make CMakeFiles/paper_lib.dir/paper/lib/utility.cpp.i
	$(MAKE) -f CMakeFiles/paper_lib_static.dir/build.make CMakeFiles/paper_lib_static.dir/paper/lib/utility.cpp.i
.PHONY : paper/lib/utility.cpp.i

paper/lib/utility.s: paper/lib/utility.cpp.s

.PHONY : paper/lib/utility.s

# target to generate assembly for a file
paper/lib/utility.cpp.s:
	$(MAKE) -f CMakeFiles/paper_lib.dir/build.make CMakeFiles/paper_lib.dir/paper/lib/utility.cpp.s
	$(MAKE) -f CMakeFiles/paper_lib_static.dir/build.make CMakeFiles/paper_lib_static.dir/paper/lib/utility.cpp.s
.PHONY : paper/lib/utility.cpp.s

paper/lib/work.o: paper/lib/work.cpp.o

.PHONY : paper/lib/work.o

# target to build an object file
paper/lib/work.cpp.o:
	$(MAKE) -f CMakeFiles/paper_lib.dir/build.make CMakeFiles/paper_lib.dir/paper/lib/work.cpp.o
	$(MAKE) -f CMakeFiles/paper_lib_static.dir/build.make CMakeFiles/paper_lib_static.dir/paper/lib/work.cpp.o
.PHONY : paper/lib/work.cpp.o

paper/lib/work.i: paper/lib/work.cpp.i

.PHONY : paper/lib/work.i

# target to preprocess a source file
paper/lib/work.cpp.i:
	$(MAKE) -f CMakeFiles/paper_lib.dir/build.make CMakeFiles/paper_lib.dir/paper/lib/work.cpp.i
	$(MAKE) -f CMakeFiles/paper_lib_static.dir/build.make CMakeFiles/paper_lib_static.dir/paper/lib/work.cpp.i
.PHONY : paper/lib/work.cpp.i

paper/lib/work.s: paper/lib/work.cpp.s

.PHONY : paper/lib/work.s

# target to generate assembly for a file
paper/lib/work.cpp.s:
	$(MAKE) -f CMakeFiles/paper_lib.dir/build.make CMakeFiles/paper_lib.dir/paper/lib/work.cpp.s
	$(MAKE) -f CMakeFiles/paper_lib_static.dir/build.make CMakeFiles/paper_lib_static.dir/paper/lib/work.cpp.s
.PHONY : paper/lib/work.cpp.s

paper/node/bootstrap.o: paper/node/bootstrap.cpp.o

.PHONY : paper/node/bootstrap.o

# target to build an object file
paper/node/bootstrap.cpp.o:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/paper/node/bootstrap.cpp.o
.PHONY : paper/node/bootstrap.cpp.o

paper/node/bootstrap.i: paper/node/bootstrap.cpp.i

.PHONY : paper/node/bootstrap.i

# target to preprocess a source file
paper/node/bootstrap.cpp.i:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/paper/node/bootstrap.cpp.i
.PHONY : paper/node/bootstrap.cpp.i

paper/node/bootstrap.s: paper/node/bootstrap.cpp.s

.PHONY : paper/node/bootstrap.s

# target to generate assembly for a file
paper/node/bootstrap.cpp.s:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/paper/node/bootstrap.cpp.s
.PHONY : paper/node/bootstrap.cpp.s

paper/node/common.o: paper/node/common.cpp.o

.PHONY : paper/node/common.o

# target to build an object file
paper/node/common.cpp.o:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/paper/node/common.cpp.o
.PHONY : paper/node/common.cpp.o

paper/node/common.i: paper/node/common.cpp.i

.PHONY : paper/node/common.i

# target to preprocess a source file
paper/node/common.cpp.i:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/paper/node/common.cpp.i
.PHONY : paper/node/common.cpp.i

paper/node/common.s: paper/node/common.cpp.s

.PHONY : paper/node/common.s

# target to generate assembly for a file
paper/node/common.cpp.s:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/paper/node/common.cpp.s
.PHONY : paper/node/common.cpp.s

paper/node/node.o: paper/node/node.cpp.o

.PHONY : paper/node/node.o

# target to build an object file
paper/node/node.cpp.o:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/paper/node/node.cpp.o
.PHONY : paper/node/node.cpp.o

paper/node/node.i: paper/node/node.cpp.i

.PHONY : paper/node/node.i

# target to preprocess a source file
paper/node/node.cpp.i:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/paper/node/node.cpp.i
.PHONY : paper/node/node.cpp.i

paper/node/node.s: paper/node/node.cpp.s

.PHONY : paper/node/node.s

# target to generate assembly for a file
paper/node/node.cpp.s:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/paper/node/node.cpp.s
.PHONY : paper/node/node.cpp.s

paper/node/openclwork.o: paper/node/openclwork.cpp.o

.PHONY : paper/node/openclwork.o

# target to build an object file
paper/node/openclwork.cpp.o:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/paper/node/openclwork.cpp.o
.PHONY : paper/node/openclwork.cpp.o

paper/node/openclwork.i: paper/node/openclwork.cpp.i

.PHONY : paper/node/openclwork.i

# target to preprocess a source file
paper/node/openclwork.cpp.i:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/paper/node/openclwork.cpp.i
.PHONY : paper/node/openclwork.cpp.i

paper/node/openclwork.s: paper/node/openclwork.cpp.s

.PHONY : paper/node/openclwork.s

# target to generate assembly for a file
paper/node/openclwork.cpp.s:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/paper/node/openclwork.cpp.s
.PHONY : paper/node/openclwork.cpp.s

paper/node/rpc.o: paper/node/rpc.cpp.o

.PHONY : paper/node/rpc.o

# target to build an object file
paper/node/rpc.cpp.o:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/paper/node/rpc.cpp.o
.PHONY : paper/node/rpc.cpp.o

paper/node/rpc.i: paper/node/rpc.cpp.i

.PHONY : paper/node/rpc.i

# target to preprocess a source file
paper/node/rpc.cpp.i:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/paper/node/rpc.cpp.i
.PHONY : paper/node/rpc.cpp.i

paper/node/rpc.s: paper/node/rpc.cpp.s

.PHONY : paper/node/rpc.s

# target to generate assembly for a file
paper/node/rpc.cpp.s:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/paper/node/rpc.cpp.s
.PHONY : paper/node/rpc.cpp.s

paper/node/testing.o: paper/node/testing.cpp.o

.PHONY : paper/node/testing.o

# target to build an object file
paper/node/testing.cpp.o:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/paper/node/testing.cpp.o
.PHONY : paper/node/testing.cpp.o

paper/node/testing.i: paper/node/testing.cpp.i

.PHONY : paper/node/testing.i

# target to preprocess a source file
paper/node/testing.cpp.i:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/paper/node/testing.cpp.i
.PHONY : paper/node/testing.cpp.i

paper/node/testing.s: paper/node/testing.cpp.s

.PHONY : paper/node/testing.s

# target to generate assembly for a file
paper/node/testing.cpp.s:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/paper/node/testing.cpp.s
.PHONY : paper/node/testing.cpp.s

paper/node/utility.o: paper/node/utility.cpp.o

.PHONY : paper/node/utility.o

# target to build an object file
paper/node/utility.cpp.o:
	$(MAKE) -f CMakeFiles/secure.dir/build.make CMakeFiles/secure.dir/paper/node/utility.cpp.o
.PHONY : paper/node/utility.cpp.o

paper/node/utility.i: paper/node/utility.cpp.i

.PHONY : paper/node/utility.i

# target to preprocess a source file
paper/node/utility.cpp.i:
	$(MAKE) -f CMakeFiles/secure.dir/build.make CMakeFiles/secure.dir/paper/node/utility.cpp.i
.PHONY : paper/node/utility.cpp.i

paper/node/utility.s: paper/node/utility.cpp.s

.PHONY : paper/node/utility.s

# target to generate assembly for a file
paper/node/utility.cpp.s:
	$(MAKE) -f CMakeFiles/secure.dir/build.make CMakeFiles/secure.dir/paper/node/utility.cpp.s
.PHONY : paper/node/utility.cpp.s

paper/node/wallet.o: paper/node/wallet.cpp.o

.PHONY : paper/node/wallet.o

# target to build an object file
paper/node/wallet.cpp.o:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/paper/node/wallet.cpp.o
.PHONY : paper/node/wallet.cpp.o

paper/node/wallet.i: paper/node/wallet.cpp.i

.PHONY : paper/node/wallet.i

# target to preprocess a source file
paper/node/wallet.cpp.i:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/paper/node/wallet.cpp.i
.PHONY : paper/node/wallet.cpp.i

paper/node/wallet.s: paper/node/wallet.cpp.s

.PHONY : paper/node/wallet.s

# target to generate assembly for a file
paper/node/wallet.cpp.s:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/paper/node/wallet.cpp.s
.PHONY : paper/node/wallet.cpp.s

paper/paper_node/daemon.o: paper/paper_node/daemon.cpp.o

.PHONY : paper/paper_node/daemon.o

# target to build an object file
paper/paper_node/daemon.cpp.o:
	$(MAKE) -f CMakeFiles/paper_node.dir/build.make CMakeFiles/paper_node.dir/paper/paper_node/daemon.cpp.o
.PHONY : paper/paper_node/daemon.cpp.o

paper/paper_node/daemon.i: paper/paper_node/daemon.cpp.i

.PHONY : paper/paper_node/daemon.i

# target to preprocess a source file
paper/paper_node/daemon.cpp.i:
	$(MAKE) -f CMakeFiles/paper_node.dir/build.make CMakeFiles/paper_node.dir/paper/paper_node/daemon.cpp.i
.PHONY : paper/paper_node/daemon.cpp.i

paper/paper_node/daemon.s: paper/paper_node/daemon.cpp.s

.PHONY : paper/paper_node/daemon.s

# target to generate assembly for a file
paper/paper_node/daemon.cpp.s:
	$(MAKE) -f CMakeFiles/paper_node.dir/build.make CMakeFiles/paper_node.dir/paper/paper_node/daemon.cpp.s
.PHONY : paper/paper_node/daemon.cpp.s

paper/paper_node/entry.o: paper/paper_node/entry.cpp.o

.PHONY : paper/paper_node/entry.o

# target to build an object file
paper/paper_node/entry.cpp.o:
	$(MAKE) -f CMakeFiles/paper_node.dir/build.make CMakeFiles/paper_node.dir/paper/paper_node/entry.cpp.o
.PHONY : paper/paper_node/entry.cpp.o

paper/paper_node/entry.i: paper/paper_node/entry.cpp.i

.PHONY : paper/paper_node/entry.i

# target to preprocess a source file
paper/paper_node/entry.cpp.i:
	$(MAKE) -f CMakeFiles/paper_node.dir/build.make CMakeFiles/paper_node.dir/paper/paper_node/entry.cpp.i
.PHONY : paper/paper_node/entry.cpp.i

paper/paper_node/entry.s: paper/paper_node/entry.cpp.s

.PHONY : paper/paper_node/entry.s

# target to generate assembly for a file
paper/paper_node/entry.cpp.s:
	$(MAKE) -f CMakeFiles/paper_node.dir/build.make CMakeFiles/paper_node.dir/paper/paper_node/entry.cpp.s
.PHONY : paper/paper_node/entry.cpp.s

paper/plat/default/priority.o: paper/plat/default/priority.cpp.o

.PHONY : paper/plat/default/priority.o

# target to build an object file
paper/plat/default/priority.cpp.o:
	$(MAKE) -f CMakeFiles/paper_lib.dir/build.make CMakeFiles/paper_lib.dir/paper/plat/default/priority.cpp.o
	$(MAKE) -f CMakeFiles/paper_lib_static.dir/build.make CMakeFiles/paper_lib_static.dir/paper/plat/default/priority.cpp.o
.PHONY : paper/plat/default/priority.cpp.o

paper/plat/default/priority.i: paper/plat/default/priority.cpp.i

.PHONY : paper/plat/default/priority.i

# target to preprocess a source file
paper/plat/default/priority.cpp.i:
	$(MAKE) -f CMakeFiles/paper_lib.dir/build.make CMakeFiles/paper_lib.dir/paper/plat/default/priority.cpp.i
	$(MAKE) -f CMakeFiles/paper_lib_static.dir/build.make CMakeFiles/paper_lib_static.dir/paper/plat/default/priority.cpp.i
.PHONY : paper/plat/default/priority.cpp.i

paper/plat/default/priority.s: paper/plat/default/priority.cpp.s

.PHONY : paper/plat/default/priority.s

# target to generate assembly for a file
paper/plat/default/priority.cpp.s:
	$(MAKE) -f CMakeFiles/paper_lib.dir/build.make CMakeFiles/paper_lib.dir/paper/plat/default/priority.cpp.s
	$(MAKE) -f CMakeFiles/paper_lib_static.dir/build.make CMakeFiles/paper_lib_static.dir/paper/plat/default/priority.cpp.s
.PHONY : paper/plat/default/priority.cpp.s

paper/plat/osx/working.o: paper/plat/osx/working.mm.o

.PHONY : paper/plat/osx/working.o

# target to build an object file
paper/plat/osx/working.mm.o:
	$(MAKE) -f CMakeFiles/secure.dir/build.make CMakeFiles/secure.dir/paper/plat/osx/working.mm.o
.PHONY : paper/plat/osx/working.mm.o

paper/plat/osx/working.i: paper/plat/osx/working.mm.i

.PHONY : paper/plat/osx/working.i

# target to preprocess a source file
paper/plat/osx/working.mm.i:
	$(MAKE) -f CMakeFiles/secure.dir/build.make CMakeFiles/secure.dir/paper/plat/osx/working.mm.i
.PHONY : paper/plat/osx/working.mm.i

paper/plat/osx/working.s: paper/plat/osx/working.mm.s

.PHONY : paper/plat/osx/working.s

# target to generate assembly for a file
paper/plat/osx/working.mm.s:
	$(MAKE) -f CMakeFiles/secure.dir/build.make CMakeFiles/secure.dir/paper/plat/osx/working.mm.s
.PHONY : paper/plat/osx/working.mm.s

paper/versioning.o: paper/versioning.cpp.o

.PHONY : paper/versioning.o

# target to build an object file
paper/versioning.cpp.o:
	$(MAKE) -f CMakeFiles/secure.dir/build.make CMakeFiles/secure.dir/paper/versioning.cpp.o
.PHONY : paper/versioning.cpp.o

paper/versioning.i: paper/versioning.cpp.i

.PHONY : paper/versioning.i

# target to preprocess a source file
paper/versioning.cpp.i:
	$(MAKE) -f CMakeFiles/secure.dir/build.make CMakeFiles/secure.dir/paper/versioning.cpp.i
.PHONY : paper/versioning.cpp.i

paper/versioning.s: paper/versioning.cpp.s

.PHONY : paper/versioning.s

# target to generate assembly for a file
paper/versioning.cpp.s:
	$(MAKE) -f CMakeFiles/secure.dir/build.make CMakeFiles/secure.dir/paper/versioning.cpp.s
.PHONY : paper/versioning.cpp.s

phc-winner-argon2/src/argon2.o: phc-winner-argon2/src/argon2.c.o

.PHONY : phc-winner-argon2/src/argon2.o

# target to build an object file
phc-winner-argon2/src/argon2.c.o:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/phc-winner-argon2/src/argon2.c.o
.PHONY : phc-winner-argon2/src/argon2.c.o

phc-winner-argon2/src/argon2.i: phc-winner-argon2/src/argon2.c.i

.PHONY : phc-winner-argon2/src/argon2.i

# target to preprocess a source file
phc-winner-argon2/src/argon2.c.i:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/phc-winner-argon2/src/argon2.c.i
.PHONY : phc-winner-argon2/src/argon2.c.i

phc-winner-argon2/src/argon2.s: phc-winner-argon2/src/argon2.c.s

.PHONY : phc-winner-argon2/src/argon2.s

# target to generate assembly for a file
phc-winner-argon2/src/argon2.c.s:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/phc-winner-argon2/src/argon2.c.s
.PHONY : phc-winner-argon2/src/argon2.c.s

phc-winner-argon2/src/core.o: phc-winner-argon2/src/core.c.o

.PHONY : phc-winner-argon2/src/core.o

# target to build an object file
phc-winner-argon2/src/core.c.o:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/phc-winner-argon2/src/core.c.o
.PHONY : phc-winner-argon2/src/core.c.o

phc-winner-argon2/src/core.i: phc-winner-argon2/src/core.c.i

.PHONY : phc-winner-argon2/src/core.i

# target to preprocess a source file
phc-winner-argon2/src/core.c.i:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/phc-winner-argon2/src/core.c.i
.PHONY : phc-winner-argon2/src/core.c.i

phc-winner-argon2/src/core.s: phc-winner-argon2/src/core.c.s

.PHONY : phc-winner-argon2/src/core.s

# target to generate assembly for a file
phc-winner-argon2/src/core.c.s:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/phc-winner-argon2/src/core.c.s
.PHONY : phc-winner-argon2/src/core.c.s

phc-winner-argon2/src/encoding.o: phc-winner-argon2/src/encoding.c.o

.PHONY : phc-winner-argon2/src/encoding.o

# target to build an object file
phc-winner-argon2/src/encoding.c.o:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/phc-winner-argon2/src/encoding.c.o
.PHONY : phc-winner-argon2/src/encoding.c.o

phc-winner-argon2/src/encoding.i: phc-winner-argon2/src/encoding.c.i

.PHONY : phc-winner-argon2/src/encoding.i

# target to preprocess a source file
phc-winner-argon2/src/encoding.c.i:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/phc-winner-argon2/src/encoding.c.i
.PHONY : phc-winner-argon2/src/encoding.c.i

phc-winner-argon2/src/encoding.s: phc-winner-argon2/src/encoding.c.s

.PHONY : phc-winner-argon2/src/encoding.s

# target to generate assembly for a file
phc-winner-argon2/src/encoding.c.s:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/phc-winner-argon2/src/encoding.c.s
.PHONY : phc-winner-argon2/src/encoding.c.s

phc-winner-argon2/src/opt.o: phc-winner-argon2/src/opt.c.o

.PHONY : phc-winner-argon2/src/opt.o

# target to build an object file
phc-winner-argon2/src/opt.c.o:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/phc-winner-argon2/src/opt.c.o
.PHONY : phc-winner-argon2/src/opt.c.o

phc-winner-argon2/src/opt.i: phc-winner-argon2/src/opt.c.i

.PHONY : phc-winner-argon2/src/opt.i

# target to preprocess a source file
phc-winner-argon2/src/opt.c.i:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/phc-winner-argon2/src/opt.c.i
.PHONY : phc-winner-argon2/src/opt.c.i

phc-winner-argon2/src/opt.s: phc-winner-argon2/src/opt.c.s

.PHONY : phc-winner-argon2/src/opt.s

# target to generate assembly for a file
phc-winner-argon2/src/opt.c.s:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/phc-winner-argon2/src/opt.c.s
.PHONY : phc-winner-argon2/src/opt.c.s

phc-winner-argon2/src/thread.o: phc-winner-argon2/src/thread.c.o

.PHONY : phc-winner-argon2/src/thread.o

# target to build an object file
phc-winner-argon2/src/thread.c.o:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/phc-winner-argon2/src/thread.c.o
.PHONY : phc-winner-argon2/src/thread.c.o

phc-winner-argon2/src/thread.i: phc-winner-argon2/src/thread.c.i

.PHONY : phc-winner-argon2/src/thread.i

# target to preprocess a source file
phc-winner-argon2/src/thread.c.i:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/phc-winner-argon2/src/thread.c.i
.PHONY : phc-winner-argon2/src/thread.c.i

phc-winner-argon2/src/thread.s: phc-winner-argon2/src/thread.c.s

.PHONY : phc-winner-argon2/src/thread.s

# target to generate assembly for a file
phc-winner-argon2/src/thread.c.s:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/phc-winner-argon2/src/thread.c.s
.PHONY : phc-winner-argon2/src/thread.c.s

xxhash/xxhash.o: xxhash/xxhash.c.o

.PHONY : xxhash/xxhash.o

# target to build an object file
xxhash/xxhash.c.o:
	$(MAKE) -f CMakeFiles/xxhash.dir/build.make CMakeFiles/xxhash.dir/xxhash/xxhash.c.o
.PHONY : xxhash/xxhash.c.o

xxhash/xxhash.i: xxhash/xxhash.c.i

.PHONY : xxhash/xxhash.i

# target to preprocess a source file
xxhash/xxhash.c.i:
	$(MAKE) -f CMakeFiles/xxhash.dir/build.make CMakeFiles/xxhash.dir/xxhash/xxhash.c.i
.PHONY : xxhash/xxhash.c.i

xxhash/xxhash.s: xxhash/xxhash.c.s

.PHONY : xxhash/xxhash.s

# target to generate assembly for a file
xxhash/xxhash.c.s:
	$(MAKE) -f CMakeFiles/xxhash.dir/build.make CMakeFiles/xxhash.dir/xxhash/xxhash.c.s
.PHONY : xxhash/xxhash.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... package_source"
	@echo "... paper_node"
	@echo "... paper_lib"
	@echo "... install"
	@echo "... blake2"
	@echo "... paper_lib_static"
	@echo "... secure"
	@echo "... ed25519"
	@echo "... install/strip"
	@echo "... package"
	@echo "... lmdb"
	@echo "... xxhash"
	@echo "... node"
	@echo "... argon2"
	@echo "... cryptopp"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... testupnpreplyparse"
	@echo "... testminiwget"
	@echo "... testigddescparse"
	@echo "... upnpc-static"
	@echo "... minixmlvalid"
	@echo "... testminixml"
	@echo "... libminiupnpc-static"
	@echo "... blake2/blake2b.o"
	@echo "... blake2/blake2b.i"
	@echo "... blake2/blake2b.s"
	@echo "... bootstrap_weights.o"
	@echo "... bootstrap_weights.i"
	@echo "... bootstrap_weights.s"
	@echo "... cryptopp/algparam.o"
	@echo "... cryptopp/algparam.i"
	@echo "... cryptopp/algparam.s"
	@echo "... cryptopp/asn.o"
	@echo "... cryptopp/asn.i"
	@echo "... cryptopp/asn.s"
	@echo "... cryptopp/basecode.o"
	@echo "... cryptopp/basecode.i"
	@echo "... cryptopp/basecode.s"
	@echo "... cryptopp/cpu.o"
	@echo "... cryptopp/cpu.i"
	@echo "... cryptopp/cpu.s"
	@echo "... cryptopp/cryptlib.o"
	@echo "... cryptopp/cryptlib.i"
	@echo "... cryptopp/cryptlib.s"
	@echo "... cryptopp/default.o"
	@echo "... cryptopp/default.i"
	@echo "... cryptopp/default.s"
	@echo "... cryptopp/des.o"
	@echo "... cryptopp/des.i"
	@echo "... cryptopp/des.s"
	@echo "... cryptopp/dessp.o"
	@echo "... cryptopp/dessp.i"
	@echo "... cryptopp/dessp.s"
	@echo "... cryptopp/dll.o"
	@echo "... cryptopp/dll.i"
	@echo "... cryptopp/dll.s"
	@echo "... cryptopp/ec2n.o"
	@echo "... cryptopp/ec2n.i"
	@echo "... cryptopp/ec2n.s"
	@echo "... cryptopp/ecp.o"
	@echo "... cryptopp/ecp.i"
	@echo "... cryptopp/ecp.s"
	@echo "... cryptopp/filters.o"
	@echo "... cryptopp/filters.i"
	@echo "... cryptopp/filters.s"
	@echo "... cryptopp/fips140.o"
	@echo "... cryptopp/fips140.i"
	@echo "... cryptopp/fips140.s"
	@echo "... cryptopp/gcm.o"
	@echo "... cryptopp/gcm.i"
	@echo "... cryptopp/gcm.s"
	@echo "... cryptopp/gf2n.o"
	@echo "... cryptopp/gf2n.i"
	@echo "... cryptopp/gf2n.s"
	@echo "... cryptopp/gfpcrypt.o"
	@echo "... cryptopp/gfpcrypt.i"
	@echo "... cryptopp/gfpcrypt.s"
	@echo "... cryptopp/hex.o"
	@echo "... cryptopp/hex.i"
	@echo "... cryptopp/hex.s"
	@echo "... cryptopp/hmac.o"
	@echo "... cryptopp/hmac.i"
	@echo "... cryptopp/hmac.s"
	@echo "... cryptopp/hrtimer.o"
	@echo "... cryptopp/hrtimer.i"
	@echo "... cryptopp/hrtimer.s"
	@echo "... cryptopp/integer.o"
	@echo "... cryptopp/integer.i"
	@echo "... cryptopp/integer.s"
	@echo "... cryptopp/iterhash.o"
	@echo "... cryptopp/iterhash.i"
	@echo "... cryptopp/iterhash.s"
	@echo "... cryptopp/misc.o"
	@echo "... cryptopp/misc.i"
	@echo "... cryptopp/misc.s"
	@echo "... cryptopp/modes.o"
	@echo "... cryptopp/modes.i"
	@echo "... cryptopp/modes.s"
	@echo "... cryptopp/mqueue.o"
	@echo "... cryptopp/mqueue.i"
	@echo "... cryptopp/mqueue.s"
	@echo "... cryptopp/nbtheory.o"
	@echo "... cryptopp/nbtheory.i"
	@echo "... cryptopp/nbtheory.s"
	@echo "... cryptopp/oaep.o"
	@echo "... cryptopp/oaep.i"
	@echo "... cryptopp/oaep.s"
	@echo "... cryptopp/osrng.o"
	@echo "... cryptopp/osrng.i"
	@echo "... cryptopp/osrng.s"
	@echo "... cryptopp/pubkey.o"
	@echo "... cryptopp/pubkey.i"
	@echo "... cryptopp/pubkey.s"
	@echo "... cryptopp/queue.o"
	@echo "... cryptopp/queue.i"
	@echo "... cryptopp/queue.s"
	@echo "... cryptopp/randpool.o"
	@echo "... cryptopp/randpool.i"
	@echo "... cryptopp/randpool.s"
	@echo "... cryptopp/rdtables.o"
	@echo "... cryptopp/rdtables.i"
	@echo "... cryptopp/rdtables.s"
	@echo "... cryptopp/rijndael.o"
	@echo "... cryptopp/rijndael.i"
	@echo "... cryptopp/rijndael.s"
	@echo "... cryptopp/rng.o"
	@echo "... cryptopp/rng.i"
	@echo "... cryptopp/rng.s"
	@echo "... cryptopp/sha.o"
	@echo "... cryptopp/sha.i"
	@echo "... cryptopp/sha.s"
	@echo "... cryptopp/simple.o"
	@echo "... cryptopp/simple.i"
	@echo "... cryptopp/simple.s"
	@echo "... cryptopp/winpipes.o"
	@echo "... cryptopp/winpipes.i"
	@echo "... cryptopp/winpipes.s"
	@echo "... ed25519-donna/ed25519.o"
	@echo "... ed25519-donna/ed25519.i"
	@echo "... ed25519-donna/ed25519.s"
	@echo "... lmdb/libraries/liblmdb/mdb.o"
	@echo "... lmdb/libraries/liblmdb/mdb.i"
	@echo "... lmdb/libraries/liblmdb/mdb.s"
	@echo "... lmdb/libraries/liblmdb/midl.o"
	@echo "... lmdb/libraries/liblmdb/midl.i"
	@echo "... lmdb/libraries/liblmdb/midl.s"
	@echo "... paper/blockstore.o"
	@echo "... paper/blockstore.i"
	@echo "... paper/blockstore.s"
	@echo "... paper/common.o"
	@echo "... paper/common.i"
	@echo "... paper/common.s"
	@echo "... paper/ledger.o"
	@echo "... paper/ledger.i"
	@echo "... paper/ledger.s"
	@echo "... paper/lib/blocks.o"
	@echo "... paper/lib/blocks.i"
	@echo "... paper/lib/blocks.s"
	@echo "... paper/lib/interface.o"
	@echo "... paper/lib/interface.i"
	@echo "... paper/lib/interface.s"
	@echo "... paper/lib/numbers.o"
	@echo "... paper/lib/numbers.i"
	@echo "... paper/lib/numbers.s"
	@echo "... paper/lib/utility.o"
	@echo "... paper/lib/utility.i"
	@echo "... paper/lib/utility.s"
	@echo "... paper/lib/work.o"
	@echo "... paper/lib/work.i"
	@echo "... paper/lib/work.s"
	@echo "... paper/node/bootstrap.o"
	@echo "... paper/node/bootstrap.i"
	@echo "... paper/node/bootstrap.s"
	@echo "... paper/node/common.o"
	@echo "... paper/node/common.i"
	@echo "... paper/node/common.s"
	@echo "... paper/node/node.o"
	@echo "... paper/node/node.i"
	@echo "... paper/node/node.s"
	@echo "... paper/node/openclwork.o"
	@echo "... paper/node/openclwork.i"
	@echo "... paper/node/openclwork.s"
	@echo "... paper/node/rpc.o"
	@echo "... paper/node/rpc.i"
	@echo "... paper/node/rpc.s"
	@echo "... paper/node/testing.o"
	@echo "... paper/node/testing.i"
	@echo "... paper/node/testing.s"
	@echo "... paper/node/utility.o"
	@echo "... paper/node/utility.i"
	@echo "... paper/node/utility.s"
	@echo "... paper/node/wallet.o"
	@echo "... paper/node/wallet.i"
	@echo "... paper/node/wallet.s"
	@echo "... paper/paper_node/daemon.o"
	@echo "... paper/paper_node/daemon.i"
	@echo "... paper/paper_node/daemon.s"
	@echo "... paper/paper_node/entry.o"
	@echo "... paper/paper_node/entry.i"
	@echo "... paper/paper_node/entry.s"
	@echo "... paper/plat/default/priority.o"
	@echo "... paper/plat/default/priority.i"
	@echo "... paper/plat/default/priority.s"
	@echo "... paper/plat/osx/working.o"
	@echo "... paper/plat/osx/working.i"
	@echo "... paper/plat/osx/working.s"
	@echo "... paper/versioning.o"
	@echo "... paper/versioning.i"
	@echo "... paper/versioning.s"
	@echo "... phc-winner-argon2/src/argon2.o"
	@echo "... phc-winner-argon2/src/argon2.i"
	@echo "... phc-winner-argon2/src/argon2.s"
	@echo "... phc-winner-argon2/src/core.o"
	@echo "... phc-winner-argon2/src/core.i"
	@echo "... phc-winner-argon2/src/core.s"
	@echo "... phc-winner-argon2/src/encoding.o"
	@echo "... phc-winner-argon2/src/encoding.i"
	@echo "... phc-winner-argon2/src/encoding.s"
	@echo "... phc-winner-argon2/src/opt.o"
	@echo "... phc-winner-argon2/src/opt.i"
	@echo "... phc-winner-argon2/src/opt.s"
	@echo "... phc-winner-argon2/src/thread.o"
	@echo "... phc-winner-argon2/src/thread.i"
	@echo "... phc-winner-argon2/src/thread.s"
	@echo "... xxhash/xxhash.o"
	@echo "... xxhash/xxhash.i"
	@echo "... xxhash/xxhash.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

